apiVersion: "skaffold/v4beta13"
kind: Config

build:
  tagPolicy:
    sha256: {}

  artifacts:
    - image: http-backend
      context: .
      docker:
        dockerfile: apps/http-backend/dockerfile
      sync:
       infer:
        - "apps/http-backend/src/**"

    - image: trading-engine
      context: .
      docker:
        dockerfile: apps/trading-engine/dockerfile
      sync:
       infer:
        - "apps/trading-engine/src/**"

    - image: price-poller
      context: .
      docker:
        dockerfile: apps/price-poller/dockerfile
      sync:
       infer:
        - "apps/price-poller/src/**"

    - image: ws-backend
      context: .
      docker:
        dockerfile: apps/ws-backend/dockerfile
      sync:
       infer:
        - "apps/ws-backend/src/**"

    - image: db-poller
      context: .
      docker:
        dockerfile: apps/db-poller/dockerfile
      sync:
       infer:
        - "apps/db-poller/src/**"

    - image: frontend
      context: .
      docker:
        dockerfile: apps/frontend/dockerfile
      sync:
       infer:
        - "apps/frontend/src/**"

manifests:
  rawYaml:
    - k8s/secret.yml

    - k8s/http-backend-deployment.yml
    - k8s/http-backend-service.yml

    - k8s/trading-engine-deployment.yml
    - k8s/trading-engine-service.yml

    - k8s/price-poller-deployment.yml
    - k8s/price-poller-service.yml

    - k8s/ws-backend-deployment.yml
    - k8s/ws-backend-service.yml

    - k8s/db-poller-deployment.yml
    - k8s/db-poller-service.yml

    - k8s/frontend-deployment.yml
    - k8s/frontend-service.yml

    - k8s/ingress.yml

portForward:
  - resourceType: service
    resourceName: frontend
    port: 80
    localPort: 5173