apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  DATABASE_URL: "postgresql://prisma:mysecret@localhost.docker.internal:5432/exchanges"
  REDIS_URL: "redis://localhost.docker.internal:6379"

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: exchange
  ADMIN_SECRET: exchange

---

apiVersion: v1
kind: Secret
metadata:
  name: frontend
type: Opaque
stringData:
  VITE_WS_URL: ws://localhost:8080
  VITE_API_URL: /api/v1
  API_PROXY_TARGET: http://http-backend
  WS_PROXY_TARGET: ws://ws-backend

---

apiVersion: v1
kind: Secret
metadata:
  name: port
type: Opaque
stringData:
  PORT: "3000"
  WSS_PORT: "8080"

---

apiVersion: v1
kind: Secret
metadata:
  name: feeder
type: Opaque
stringData:
  PRICE_FEEDER_REST_FALLBACK: "false"